# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3'
services:
  mediawiki:
    image: mediawiki_update:1.0.0
    restart: always
    ports:
      - 8080:80
    links:
      - mysql
    volumes:
      - ./mediawiki/images:/var/www/html/w/images
      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
  mysql:
    image: mysql/mysql-server:5.7
    volumes:
      - ./mysql/conf/:/etc/mysql/
      - ./mysql/db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: wikiuser
